name: ecocharge_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  ai_barcode_scanner: ^3.4.3
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.1
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  mqtt_client: ^10.2.1
  network_to_file_image: ^6.0.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pinput: ^4.0.0
  url_launcher: ^6.2.6
  web_socket_channel: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
      - assets/images/
